version: '3'

services:
  app:
    build: 
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./output:/output
    environment:
      - VIDEO_PATH=./assets/BigBuckBunny.mp4
    ports:
      - "8000:8000"